repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.12
  hooks:
    - id: uv-lock

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: debug-statements

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        args: ['--in-place']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-case-conflict
    -   id: detect-aws-credentials
        args: ['--allow-missing-credentials']
    -   id: detect-private-key
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
    
-   repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
